---
title: "Data preparation"
date: "10 November 2020"
author: 
- "Rachel"
- "Eliane"
output: html_document
---

## Creek data 
```{r,  include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load data
f1 <- read.table("/Users/eliane/Desktop/SEM_UZH/Swiss_SEM/data_preparation/18_4_data_Welk_etal_PlosOne.csv", sep=";", header=TRUE)
f2 <- read.table("/Users/eliane/Desktop/SEM_UZH/Swiss_SEM/data_preparation/e120_Plant species percent cover data.csv", sep="\t", header=TRUE)
f3 <- read.table("/Users/eliane/Desktop/SEM_UZH/Swiss_SEM/data_preparation/e120_Plant aboveground biomass carbon and nitrogen.csv", sep="\t", header=TRUE)
f4 <- read.table("/Users/eliane/Desktop/SEM_UZH/Swiss_SEM/data_preparation/e120_Plant aboveground biomass data.csv", sep="\t", header=TRUE)
f5 <- read.table("/Users/eliane/Desktop/SEM_UZH/Swiss_SEM/data_preparation/e120_Plant traits.csv", sep="\t", header=TRUE)
f6 <- read.table("/Users/eliane/Desktop/SEM_UZH/Swiss_SEM/data_preparation/e120_Percent light penetration.csv", sep="\t", header=TRUE)
f7 <- read.table("/Users/eliane/Desktop/SEM_UZH/Swiss_SEM/data_preparation/e120_Soil carbon.csv", sep="\t", header=TRUE)
f8 <- read.table("/Users/eliane/Desktop/SEM_UZH/Swiss_SEM/data_preparation/e120_Soil nitrate and ammonium.csv", sep="\t", header=TRUE)
f9 <- read.table("/Users/eliane/Desktop/SEM_UZH/Swiss_SEM/data_preparation/e120_Soil nitrogen.csv", sep="\t", header=TRUE)

f_1 <- merge(f1, f2, by=c("Plot"), all=T)
f_2 <- merge(f_1, f3, by=c("Plot","Year"), all=T)


```


## Data from Welk et al. (2014) Biotic Interactions Overrule Plant Responses to Climate, Depending on the Species' Biogeography

We downloaded the data from https://idata.idiv.de/ddm/Data/ShowData/18



```{r,  include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load data
raw_data <- read.table("/Users/eliane/Desktop/SEM_UZH/Swiss_SEM/data_preparation/18_4_data_Welk_etal_PlosOne.csv", sep=";", header=TRUE)




```





