---
title: "Introduction to structural equation modeling"
subtitle: "Basic modelling"
author: "Frank Pennekamp"
institute:
- Department of Evolutionary Biology and Environmental Sciences
- University of Zurich
date: "`r format(Sys.time(), '%d.%m.%Y')`"
fontsize: 12pt
output: 
  beamer_presentation: 
    theme: metropolis
    keep_tex: no
    incremental: no
    latex_engine: xelatex
classoption: compress
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Introduction of the **Swiss SEM team**

- Dr. Frank Pennekamp (main instructor)   
- Dr. James Grace (advanced topics and model clinic)   
- Dr. Rachel Korn (course development)   
- Dr. Noémie Pichon, Dr. Fletcher Halliday, Dr. Eliane Meier, Dr. Hugo Saiz, Dr. Debra Zuppinger-Dingley, Rebecca Oester, Annabelle Constance, Fabienne Wiederkehr (course development)

# Schedule

- Day 1:
  * General introduction to SEM to model ecological systems
  * Fitting SEMs to data
  * Model pruning, visualization and reporting
  * Discussion with James Grace
- Day 2:
  * Latent and composite variables
  * Interactions
  * Complex sampling designs
  * Spatial autocorrelation
  * Discussion with James Grace
- Day 3:
  * Self-study with possibility to meet with instructor(s)

# Overview

What the course is about

- Global estimation with R package lavaan
- Hands on exercises and live coding
- We will work (mostly) with a single, ecological dataset

What will not be covered

- Local estimation of SEMs (with piecewiseSEM)
- Advanced topics like incorporating random effects, feedbacks, temporal autocorrelation

# Learning objectives

- Participants understand the benefits and limits of SEMs
- Participants are able to fit, interpret and visualize a SEM
- Participants are able to apply SEM to their own dataset

# Questions?




