---
title: "How to present SEMs?"
output: beamer_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Exercice

We have now analysed the model. 

How would you draw the model output to represent the minimum information required in order to reproduce this model?

\begin{center}
Draw your idea
\end{center}


# What can you expect to see out in nature?

##  Non-ecological examples

Causal inference, DAGs, Psychology

*insert SEMs*



# What can you expect to see out in nature?

## What ecologists do

Very good examples & very bad examples

*insert SEMs*



# Discussion
## What makes a good data visualization?

# Theory

*Maybe one slide drawing heavily on theory from people like Edward Tufte*

*Information/ink ratio*

# What is a good SEM drawing


Discussion: 

Starting from what you draw and what you just saw, what are the necessary information to include in an SEM?

What is missing in you drawing?


# Necessary information

There are no rules. Here are our guidelines to help drawing a good/reproducible/interpretable SEM diagram.


1) Represent your variables
1) Represent your coefficients
1) Represent all paths 
1) Report model goodness of fit
1) Report explanatory power for endogenous variables
1) Include important tables


# Necessary information
**1) Represent your variables**

Squares are data

Circles are latent variables

Hexagon (?) for composite variables

*insert illustration*

# Necessary information
**2) Represent your coefficients**

Magnitude, direction, and significance

- Change the path

Color for direction

Dashed vs solid for significance

- Change the size

Write the numbers

*insert illustration*

# Necessary information
**3) Represent all paths **

Represent causal paths included in your model regardless of significance. 
Not necessarily in the same figure.

Represent important correlations

- Exogenous can or can not be included
- Always include correlations among the errors of endogenous variables

# Necessary information
**4) Report model goodness of fit**

- Covariance-based approaches

Chi-squared

SRMR

RMSEA

- Local estimation

D-sep test

# Necessary information
**5) Explanatory power for endogenous variables**

Residual error or R2

# Necessary information
**6) Include important tables**

Coefficient table

Local estimation: basis set

Mediation analysis?



# Room for artistry 

This will depend on the audience and support:

Is this a paper?

Is this a presentation?

What is the narrative structure?

Key thing here is that one structure might not work in every case.
Not advocating for anything in particular, but note that the same model for a paper might not be the right presentation for an SEM.


# Room for artistry

Interactions,multigroup models, composites, etc.

Color, size, etc.

Organizing variables in space in a way that is useful to your reader rather than distracting:

- Top to bottom, or left to right?
- Mediator relative placement

Composite variable: do we need to show everything?

Breaking up complicated models into several panels or several figures


# Room for artistry


Meta models, apriori models, etc

- Start with something abstract (metamodel concept)
- shows the core concepts and their relationships, ignoring the data.
- The most abstracted vision of the causal process you are trying to capture



# Room for artistry

Showing the underlying data

Partial plots

Raw correlations:

- Shows linearity assumption, shows distribution of data, etc
- Correlation tables



# Building the plot 

This can be done in R. But it is generally done in external software like powerpoint, illustrator, or Inkscape.

In R, it can be useful to visualise your code and your model output.

Resources for drawing in R: <https://statistics.ohlsen-web.de/sem-path-diagram/>


