---
title: "How_to_get_started_with_SEM"
author: "FP"
date: "11/11/2020"
output: beamer_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## What is a SEM?
(https://www.r-bloggers.com/2011/05/ecological-sems-and-composite-variables-what-why-and-how/)
Comments:
Each slide represents a concept/topic to teach. Can be expanded to more slides.
Content must be revisited to be consistent in wording, concepts etc.
Specially required feedback on causality, meta-model, backdoor criterion, loops.
Concepts for technical part that could be introduced also here: global vs local, information criteria for arrow selection (for me better on technical part).

## What is a SEM?

Here we ask students about what is a SEM, why they want to learn them etc.

Examine relative influences and responses
In SEM specification of a model, to determine and validify a proposed causal process and/or model, is based on theory and research.
Two goals in SEM are
1) to understand the patterns of correlation/covariance among a set of variables and
2) to explain as much of their variance as possible with the model specified (Kline, 1998).


## Why do we need to use SEM in Ecology

To better understand the relationship among variables in complex ecosystems:
We use multiple observed variables 
Test and evaluate multivariate causal relationships
Test direct and indirect effects on pre-assumed causal relationships
Incorporate both latent and observed variables
Including interaction terms can test main effects and interaction effects

## Research questions

The importance of questions in science -> 
We are scientists and we try to explain the reality surrounding us.
In this course, the focus is in ecology and evolution.
.

## Example of the working system

Cedar Creek Ecosystem Science Reserve is a University of Minnesota biological field station 
Includes ecosystems and species in North American forests and grasslands 
Experiments examine long-term consequences of human-driven environmental changes
ecosystem responses to:
  Biodiversity loss
  Nitrogen deposition
  Elevated carbon dioxide
  Warming and changes in precipitation
  Exotic species invasions
 Add experiment of data we will use.
Add some nice pictures.

## SEM Steps

• review the relevant theory and research literature to support model specification
• specify a model (e.g., diagram, equations)
• determine model identification (e.g., if unique values can be found for parameter estimation; the number of degrees of
freedom, df, for model testing is positive)
• select measures for the variables represented in the model
• collect data
• conduct preliminary descriptive statistical analysis (e.g., scaling, missing data, collinearity issues, outlier detection)
• estimate parameters in the model
• assess model fit
• respecify the model if meaningful
• interpret and present results## Graphical representation

## Question of interest

Present one research question based on the data.
This question only NEEDS to include 2 variables.
Ask students about how they would address this question.

## Introduce the graphical model representation (X -> Y):
- Variables are nodes.
- Arrows are causal relationships.
Use the question in the previous part as example.

## Causality

What is a causal relationship?
Correlation does not imply causation, causation indicates a relation between two variables in which one variable is affected by another.
The arrow mean causality.
Is it the case in science?
Explain the concept and discuss with students the topic.
Show the difference between direct effects and correlation together with the graphical representation

## Simple statistical model

Present the bivariate model.
Include the equation and a plot.
It is important that students understand that all they know can be defined with a graphical representation.

## Multivariate questions

Discuss with students other variables that may affect B.
Introduce a new variable and the question that it answers.
Show the graphical model (X1 -> Y, X2 -> Y).
Include the equation and the two partial plots.
Be clear this is a multiple regression model.

## Interaction questions (Moderation)

Present another question involving a new variable with an interactive effect (X3 -> (Y -> Z)).
Show the graphical representation.
Explanation of interactive effects.
Include partial plots to illustrate the interaction effect. 
Make clear that this is the same as an interaction in traditional regression models.

## Indirect effect (Mediation)

Present another question involving a new variable (X1 -> Y -> Z).
Show the graphical representation.
Direct effect is a directional relation between two variables, e.g., independent and dependent variables
Indirect effect is the effect of an independent variable on a dependent variable through one or more intervening or
mediating variables.
Include partial plots for both to illustrate the indirect effect. 

## Types of variables

Until now everything was about paths but modelling also involves variables.
Composite variables specify the influences of collections of other variables (examples)
A variable that is not directly measured is a latent variable (examples)
Make clear the difference between both.

## System level approach

Show a very complex model including multiple types of variables, arrows (direct and correlations) for the study system.
The complex model is built based on submodels, each one addressing specific questions.
We need a framework to analyze this together -> SEM
Discuss about complexity in ecology and if SEM is useful to answer your questions ("We need to do things as simple as possible, but no simpler").

## Assumptions of SEM 

Assumptions common to any statistical analysis (normality, amount of data, experimental design...).
Assumptions specific to SEM (data in the same scale...).

## Thinking about the model

Which variables include in the model 
- Supported by theory.
- Ecologically meaningful.
- Garbage in - garbage out concept (both data quality and ecologically meaningful).

Setting arrow direction.
- Causal vs correlation.
- Support for both directions, how to proceed (loops).

Good practice: Table of causal relationships before analysis.

## Meta-model

Thinking about what is missing in the model, measurement errors etc.
Present the concept of meta-model and impications for research.
Include a graphical representation of the meta-model as what is missing in the model.

## Modelling philosophy 

Two approaches: from theory (hypothesis) to data (exploratories).
Show as a continuum between two extremes.
Importance of being aware about what the model is telling to us.
Finall discussion about what SEM provides and the importance of system thinking in ecology.



